'use client';

import { useMemo } from 'react';

import { useSchemaBuilderSelectors } from '@/blocks/schema/schema-builder-core/lib/gql/hooks/schema-builder';
import { useDatabasePolicies } from '@/blocks/schema/schema-builder-core/lib/gql/hooks/schema-builder/policies/use-database-policies';

import { getGeneratedFieldMappings } from '@/blocks/schema/schema-builder-core/components/policies/policy-config';
import { useFormSchema } from '../policy-hooks';
import type { MergedPolicyType } from '@/blocks/schema/schema-builder-core/components/policies/policy-types';
import { AccessControlGroup } from './access-control-group';
import { AutoGeneratedFieldsInfo } from './auto-generated-fields-info';
import { DynamicFormField } from './dynamic-form-field';

const ACCESS_CONTROL_KEYS = new Set(['is_admin', 'is_owner']);

interface PolicyConfigFormProps {
	policyType: MergedPolicyType;
	value: Record<string, unknown>;
	onChange: (value: Record<string, unknown>) => void;
	disabled?: boolean;
	/** Hide the auto-generated fields info box */
	hideAutoGeneratedInfo?: boolean;
}

/**
 * Dynamic form for configuring a policy type.
 *
 * Renders fields based on the policy type's field overrides.
 * All fields are shown inline (no advanced section).
 */
export function PolicyConfigForm({
	policyType,
	value,
	onChange,
	disabled,
	hideAutoGeneratedInfo,
}: PolicyConfigFormProps) {
	const { mainFields: allMainFields, advancedFields: allAdvancedFields } = useFormSchema(policyType);

	// Fetch tables for populating table/field dropdowns
	const { currentDatabase } = useSchemaBuilderSelectors();
	const databaseId = currentDatabase?.databaseId ?? '';
	const { data: tables = [] } = useDatabasePolicies(databaseId, { enabled: Boolean(databaseId) });

	// Combine main + advanced into a single list (no collapsible section)
	const allFields = useMemo(() => [...allMainFields, ...allAdvancedFields], [allMainFields, allAdvancedFields]);

	const handleFieldChange = (key: string, fieldValue: unknown) => {
		const updates: Record<string, unknown> = { [key]: fieldValue };

		// When a table-select changes, clear fields that depend on it
		for (const f of allFields) {
			if (f.dependsOn === key) {
				updates[f.key] = f.type === 'field-multi-select' ? [] : '';
			}
		}

		onChange({ ...value, ...updates });
	};

	// Build field mappings for inline editing in auto-generated fields info
	const fieldMappings = useMemo(() => getGeneratedFieldMappings(policyType), [policyType]);

	// Get the set of policy keys that are handled by inline editing
	const inlineEditedKeys = useMemo(() => {
		if (!fieldMappings) return new Set<string>();
		return new Set(Object.values(fieldMappings).map((m) => m.policyKey));
	}, [fieldMappings]);

	// Filter out fields handled by inline editing (when auto-generated info is shown)
	const filteredFields = useMemo(() => {
		if (hideAutoGeneratedInfo) return allFields;
		return allFields.filter((field) => !inlineEditedKeys.has(field.key));
	}, [allFields, inlineEditedKeys, hideAutoGeneratedInfo]);

	// Separate access control fields (is_admin, is_owner) from the rest
	const accessControlFields = useMemo(
		() => filteredFields.filter((f) => ACCESS_CONTROL_KEYS.has(f.key)),
		[filteredFields],
	);
	const regularFields = useMemo(
		() => filteredFields.filter((f) => !ACCESS_CONTROL_KEYS.has(f.key)),
		[filteredFields],
	);

	const hasNoConfig =
		filteredFields.length === 0 && policyType.generatedFields.length === 0 && inlineEditedKeys.size === 0;

	return (
		<div data-chat-component='policy-config-form' data-chat-policy-type={policyType.name} className='space-y-4'>
			{/* Auto-generated fields notice with inline editing */}
			{!hideAutoGeneratedInfo && (
				<AutoGeneratedFieldsInfo
					fields={policyType.generatedFields}
					value={value}
					onChange={handleFieldChange}
					fieldMappings={fieldMappings}
					disabled={disabled}
				/>
			)}

			{/* Regular form fields */}
			{regularFields.length > 0 && (
				<div className='space-y-4'>
					{regularFields.map((field) => (
						<DynamicFormField
							key={field.key}
							field={field}
							value={value[field.key]}
							onChange={(v) => handleFieldChange(field.key, v)}
							disabled={disabled}
							tables={tables}
							formData={value}
						/>
					))}
				</div>
			)}

			{/* Grouped access control (is_admin / is_owner) */}
			{accessControlFields.length > 0 && (
				<AccessControlGroup
					fields={accessControlFields}
					values={value}
					onChange={handleFieldChange}
					disabled={disabled}
				/>
			)}

			{/* No configuration needed message */}
			{hasNoConfig && (
				<p className='text-muted-foreground text-sm italic'>This policy type requires no configuration.</p>
			)}
		</div>
	);
}
