import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

import { constructiveTheme, type ThemeCssObject, type ThemeTokenMap } from '../src/theme.ts';

interface RegistryItem {
	name: string;
	type: string;
	[key: string]: unknown;
}

interface RegistryManifest {
	items: RegistryItem[];
	[key: string]: unknown;
}

const packageRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const globalsPath = path.join(packageRoot, 'src', 'styles', 'globals.css');
const registryPath = path.join(packageRoot, 'registry.json');
const checkOnly = process.argv.includes('--check');

function indent(value: string, spaces = 2): string {
	const prefix = ' '.repeat(spaces);
	return value
		.split('\n')
		.map((line) => (line.length > 0 ? `${prefix}${line}` : ''))
		.join('\n');
}

function renderVariables(tokens: ThemeTokenMap): string {
	return Object.entries(tokens)
		.map(([name, value]) => `  --${name}: ${value};`)
		.join('\n');
}

function renderTailwindVariables(tokens: ThemeTokenMap): string {
	return Object.entries(tokens)
		.map(([name, value]) => `  ${name}: ${value};`)
		.join('\n');
}

function renderCssObject(css: ThemeCssObject): string {
	return Object.entries(css)
		.map(([name, value]) => {
			if (typeof value === 'string') return `${name}: ${value};`;
			if (name.startsWith('@') && Object.keys(value).length === 0) return `${name};`;
			return `${name} {\n${indent(renderCssObject(value))}\n}`;
		})
		.join('\n');
}

export function renderConstructiveGlobals(): string {
	const imports = constructiveTheme.npmImports.map((specifier) => `@import '${specifier}';`).join('\n');
	const keyframes = Object.entries(constructiveTheme.keyframes)
		.map(([name, body]) => `@keyframes ${name} {\n${indent(renderCssObject(body))}\n}`)
		.join('\n\n');

	return `/* Generated by scripts/generate-theme.ts. Edit src/theme.ts instead. */
${imports}

@source "${constructiveTheme.npmSource}";

@custom-variant dark (${constructiveTheme.darkVariant});

:root {
${renderVariables(constructiveTheme.light)}
${renderVariables(constructiveTheme.zIndex)}
}

.dark {
${renderVariables(constructiveTheme.dark)}
}

@theme inline {
${renderTailwindVariables(constructiveTheme.tailwind)}
}

@layer base {
${indent(renderCssObject(constructiveTheme.baseCss))}
}

@layer utilities {
${indent(renderCssObject(constructiveTheme.utilities))}
}

${keyframes}

${renderCssObject(constructiveTheme.globalCss)}
`;
}

export const constructiveThemeRegistryItem: RegistryItem = {
	name: 'constructive-theme',
	type: 'registry:theme',
	title: 'Constructive Theme',
	description: 'Constructive design system theme — OKLCH colors, z-index layers, shadow utilities, and animations.',
	cssVars: {
		theme: constructiveTheme.tailwind,
		light: { ...constructiveTheme.light, ...constructiveTheme.zIndex },
		dark: { ...constructiveTheme.dark, ...constructiveTheme.zIndex },
	},
	css: {
		'@layer base': constructiveTheme.baseCss,
		'@layer utilities': constructiveTheme.utilities,
		...Object.fromEntries(
			Object.entries(constructiveTheme.keyframes).map(([name, value]) => [`@keyframes ${name}`, value]),
		),
		...constructiveTheme.globalCss,
	},
	files: [],
};

function findThemeItemRange(source: string): { start: number; end: number } {
	const marker = '"name": "constructive-theme"';
	const markerIndex = source.indexOf(marker);
	if (markerIndex === -1) throw new Error('packages/ui/registry.json is missing constructive-theme');

	const start = source.lastIndexOf('{', markerIndex);
	if (start === -1) throw new Error('Could not locate the constructive-theme object start');

	let depth = 0;
	let inString = false;
	let escaped = false;
	for (let index = start; index < source.length; index += 1) {
		const character = source[index];
		if (inString) {
			if (escaped) escaped = false;
			else if (character === '\\') escaped = true;
			else if (character === '"') inString = false;
			continue;
		}
		if (character === '"') inString = true;
		else if (character === '{') depth += 1;
		else if (character === '}') {
			depth -= 1;
			if (depth === 0) return { start, end: index + 1 };
		}
	}

	throw new Error('Could not locate the constructive-theme object end');
}

function replaceThemeItemSource(source: string): string {
	const { start, end } = findThemeItemRange(source);
	const lineStart = source.lastIndexOf('\n', start) + 1;
	if (source.slice(lineStart, start).trim() !== '') throw new Error('constructive-theme must start on its own line');
	const itemSource = JSON.stringify(constructiveThemeRegistryItem, null, 2)
		.split('\n')
		.map((line) => `    ${line}`)
		.join('\n');
	return `${source.slice(0, lineStart)}${itemSource}${source.slice(end)}`;
}

async function main(): Promise<void> {
	const [currentGlobals, registrySource] = await Promise.all([
		readFile(globalsPath, 'utf8'),
		readFile(registryPath, 'utf8'),
	]);
	const expectedGlobals = renderConstructiveGlobals();
	const currentRegistry = JSON.parse(registrySource) as RegistryManifest;
	const currentThemeItem = currentRegistry.items.find((item) => item.name === 'constructive-theme');
	if (!currentThemeItem) throw new Error('packages/ui/registry.json is missing constructive-theme');
	const expectedRegistry = replaceThemeItemSource(registrySource);
	const failures: string[] = [];

	if (currentGlobals !== expectedGlobals) failures.push(path.relative(packageRoot, globalsPath));
	if (JSON.stringify(currentThemeItem) !== JSON.stringify(constructiveThemeRegistryItem)) {
		failures.push(path.relative(packageRoot, registryPath));
	}

	if (checkOnly) {
		if (failures.length > 0) {
			throw new Error(`Generated theme files are stale: ${failures.join(', ')}. Run pnpm theme:generate.`);
		}
		console.log('Constructive theme outputs are current.');
		return;
	}

	await Promise.all([
		writeFile(globalsPath, expectedGlobals, 'utf8'),
		writeFile(registryPath, expectedRegistry, 'utf8'),
	]);
	console.log(`Generated ${path.relative(packageRoot, globalsPath)} and ${path.relative(packageRoot, registryPath)}.`);
}

await main();
