import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

import { THEME_PRESETS, type ThemePreset } from '../src/theme-presets.ts';
import { constructiveTheme, type ThemeCssObject, type ThemeTokenMap } from '../src/theme.ts';

interface RegistryItem {
	name: string;
	type: string;
	[key: string]: unknown;
}

interface RegistryManifest {
	items: RegistryItem[];
	[key: string]: unknown;
}

const packageRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const globalsPath = path.join(packageRoot, 'src', 'styles', 'globals.css');
const registryPath = path.join(packageRoot, 'registry.json');
const checkOnly = process.argv.includes('--check');

function indent(value: string, spaces = 2): string {
	const prefix = ' '.repeat(spaces);
	return value
		.split('\n')
		.map((line) => (line.length > 0 ? `${prefix}${line}` : ''))
		.join('\n');
}

function renderVariables(tokens: ThemeTokenMap): string {
	return Object.entries(tokens)
		.map(([name, value]) => `  --${name}: ${value};`)
		.join('\n');
}

function renderTailwindVariables(tokens: ThemeTokenMap): string {
	return Object.entries(tokens)
		.map(([name, value]) => `  ${name}: ${value};`)
		.join('\n');
}

function renderCssObject(css: ThemeCssObject): string {
	return Object.entries(css)
		.map(([name, value]) => {
			if (typeof value === 'string') return `${name}: ${value};`;
			if (name.startsWith('@') && Object.keys(value).length === 0) return `${name};`;
			return `${name} {\n${indent(renderCssObject(value))}\n}`;
		})
		.join('\n');
}

export function renderConstructiveGlobals(): string {
	const imports = constructiveTheme.npmImports.map((specifier) => `@import '${specifier}';`).join('\n');
	const keyframes = Object.entries(constructiveTheme.keyframes)
		.map(([name, body]) => `@keyframes ${name} {\n${indent(renderCssObject(body))}\n}`)
		.join('\n\n');

	return `/* Generated by scripts/generate-theme.ts. Edit src/theme.ts instead. */
${imports}

@source "${constructiveTheme.npmSource}";

@custom-variant dark (${constructiveTheme.darkVariant});

:root {
${renderVariables(constructiveTheme.light)}
${renderVariables(constructiveTheme.zIndex)}
}

.dark {
${renderVariables(constructiveTheme.dark)}
}

@theme static {
${renderTailwindVariables(constructiveTheme.fonts)}
}

@theme inline {
${renderTailwindVariables(constructiveTheme.tailwind)}
}

@layer base {
${indent(renderCssObject(constructiveTheme.baseCss))}
}

@layer utilities {
${indent(renderCssObject(constructiveTheme.utilities))}
}

${keyframes}

${renderCssObject(constructiveTheme.globalCss)}
`;
}

export const constructiveThemeRegistryItem: RegistryItem = {
	name: 'constructive-theme',
	type: 'registry:theme',
	title: 'Constructive Theme',
	description: 'Constructive design system theme — OKLCH colors, z-index layers, shadow utilities, and animations.',
	cssVars: {
		// shadcn writes cssVars.theme as `@theme inline` — the standard flow for
		// font tokens installed through the registry.
		theme: { ...constructiveTheme.fonts, ...constructiveTheme.tailwind },
		light: { ...constructiveTheme.light, ...constructiveTheme.zIndex },
		dark: { ...constructiveTheme.dark, ...constructiveTheme.zIndex },
	},
	css: {
		'@layer base': constructiveTheme.baseCss,
		'@layer utilities': constructiveTheme.utilities,
		...Object.fromEntries(
			Object.entries(constructiveTheme.keyframes).map(([name, value]) => [`@keyframes ${name}`, value]),
		),
		...constructiveTheme.globalCss,
	},
	files: [],
};

/** One `registry:theme` item per preset, installed via `shadcn add @constructive/theme-<id>`. */
function themePresetRegistryItem(preset: ThemePreset): RegistryItem {
	return {
		name: `theme-${preset.id}`,
		type: 'registry:theme',
		title: `${preset.label} theme`,
		description: preset.description,
		categories: ['theme'],
		docs: `Install with \`pnpm dlx shadcn@latest add @constructive/theme-${preset.id}\`. Requires the Constructive base theme (\`@constructive/constructive-theme\`).`,
		cssVars: { light: preset.tokens.light, dark: preset.tokens.dark },
	};
}

const THEME_REGISTRY_ITEMS: RegistryItem[] = [
	constructiveThemeRegistryItem,
	...THEME_PRESETS.map(themePresetRegistryItem),
];

/** Remove one named item (object + its separating comma + trailing newline). */
function removeRegistryItem(source: string, name: string): string {
	const marker = `"name": "${name}"`;
	const markerIndex = source.indexOf(marker);
	if (markerIndex === -1) return source;

	const start = source.lastIndexOf('{', markerIndex);
	let depth = 0;
	let inString = false;
	let escaped = false;
	let end = -1;
	for (let index = start; index < source.length; index += 1) {
		const character = source[index];
		if (inString) {
			if (escaped) escaped = false;
			else if (character === '\\') escaped = true;
			else if (character === '"') inString = false;
			continue;
		}
		if (character === '"') inString = true;
		else if (character === '{') depth += 1;
		else if (character === '}') {
			depth -= 1;
			if (depth === 0) {
				end = index + 1;
				break;
			}
		}
	}
	if (end === -1) throw new Error(`Could not locate the ${name} object end`);

	// Items are separated as `{item},\n    {next}` — consume the trailing
	// separator comma and the rest of the item's line.
	let removeStart = start;
	while (removeStart > 0 && (source[removeStart - 1] === ' ' || source[removeStart - 1] === '\t')) {
		removeStart -= 1;
	}
	while (removeStart > 0 && source[removeStart - 1] !== '\n') removeStart -= 1;
	if (source[end] === ',') end += 1;
	if (source[end] === '\n') end += 1;
	return source.slice(0, removeStart) + source.slice(end);
}

function findThemeItemRange(source: string): { start: number; end: number } {
	const marker = '"name": "constructive-theme"';
	const markerIndex = source.indexOf(marker);
	if (markerIndex === -1) throw new Error('packages/ui/registry.json is missing constructive-theme');

	const start = source.lastIndexOf('{', markerIndex);
	if (start === -1) throw new Error('Could not locate the constructive-theme object start');

	let depth = 0;
	let inString = false;
	let escaped = false;
	for (let index = start; index < source.length; index += 1) {
		const character = source[index];
		if (inString) {
			if (escaped) escaped = false;
			else if (character === '\\') escaped = true;
			else if (character === '"') inString = false;
			continue;
		}
		if (character === '"') inString = true;
		else if (character === '{') depth += 1;
		else if (character === '}') {
			depth -= 1;
			if (depth === 0) return { start, end: index + 1 };
		}
	}

	throw new Error('Could not locate the constructive-theme object end');
}

function replaceThemeItemSource(source: string): string {
	// Drop previously generated preset items, then splice the full theme block
	// (constructive-theme + one item per preset) back in place.
	let next = source;
	for (const preset of THEME_PRESETS) {
		next = removeRegistryItem(next, `theme-${preset.id}`);
	}
	const { start, end } = findThemeItemRange(next);
	const lineStart = next.lastIndexOf('\n', start) + 1;
	if (next.slice(lineStart, start).trim() !== '') throw new Error('constructive-theme must start on its own line');
	const itemsSource = THEME_REGISTRY_ITEMS.map((item) =>
		JSON.stringify(item, null, 2)
			.split('\n')
			.map((line) => `    ${line}`)
			.join('\n'),
	).join(',\n');
	return `${next.slice(0, lineStart)}${itemsSource}${next.slice(end)}`;
}

async function main(): Promise<void> {
	const [currentGlobals, registrySource] = await Promise.all([
		readFile(globalsPath, 'utf8'),
		readFile(registryPath, 'utf8'),
	]);
	const expectedGlobals = renderConstructiveGlobals();
	const currentRegistry = JSON.parse(registrySource) as RegistryManifest;
	const currentThemeItem = currentRegistry.items.find((item) => item.name === 'constructive-theme');
	if (!currentThemeItem) throw new Error('packages/ui/registry.json is missing constructive-theme');
	const expectedRegistry = replaceThemeItemSource(registrySource);
	JSON.parse(expectedRegistry); // generated output must stay valid JSON
	const failures: string[] = [];

	if (currentGlobals !== expectedGlobals) failures.push(path.relative(packageRoot, globalsPath));
	const expectedNames = new Set(THEME_REGISTRY_ITEMS.map((item) => item.name));
	const currentThemeItems = currentRegistry.items.filter((item) => expectedNames.has(item.name));
	const themesCurrent =
		currentThemeItems.length === THEME_REGISTRY_ITEMS.length &&
		THEME_REGISTRY_ITEMS.every((expected) =>
			currentThemeItems.some((item) => JSON.stringify(item) === JSON.stringify(expected)),
		);
	if (!themesCurrent) {
		failures.push(path.relative(packageRoot, registryPath));
	}

	if (checkOnly) {
		if (failures.length > 0) {
			throw new Error(`Generated theme files are stale: ${failures.join(', ')}. Run pnpm theme:generate.`);
		}
		console.log('Constructive theme outputs are current.');
		return;
	}

	await Promise.all([
		writeFile(globalsPath, expectedGlobals, 'utf8'),
		writeFile(registryPath, expectedRegistry, 'utf8'),
	]);
	console.log(`Generated ${path.relative(packageRoot, globalsPath)} and ${path.relative(packageRoot, registryPath)}.`);
}

await main();
