// Deterministic _meta + row fixtures for the Storybook showcase.
//
// Cell type is resolved from SCHEMA META, never the value (resolveCellType). pgAlias is the
// forcing channel: setting field.type.pgAlias to a target type drives mapToFrontendCellType to
// that CellType regardless of gqlType (see cell-types/type-mapping.ts mapAliasToCellType).
// buildAllCellTypesTable emits ONE field per (forceable) CellType so the grid paints every view.
//
// Row values mirror grid/__golden__/display-cases.ts patterns (strings, numbers, booleans, ISO
// dates, arrays, {id,displayName} relations, image urls, geojson, …) but are generated by a
// seeded PRNG (mulberry32) so makeRows(n) is fully reproducible — required for a stable 10k
// stress test and visual regression.
import type { MetaTable, MetaField } from '../../forms/types';
import type { SheetsRow } from '../../grid/row-model';
import type { CellType } from '../../cell-types/types';

// ─── Seeded PRNG (mulberry32) — tiny, deterministic, NOT Math.random ─────────────────────────
function mulberry32(seed: number): () => number {
	let a = seed >>> 0;
	return function () {
		a |= 0;
		a = (a + 0x6d2b79f5) | 0;
		let t = Math.imul(a ^ (a >>> 15), 1 | a);
		t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
		return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
	};
}

// ─── Meta builders (mirror testing/mock-sheets-provider.tsx buildMetaField/buildMetaTable) ────

interface FieldSpec {
	name: string;
	gqlType: string;
	/** Forces the resolved CellType (pgAlias has top priority in mapToFrontendCellType). */
	pgAlias?: string;
	pgType?: string;
	isArray?: boolean;
	subtype?: string | null;
	isNotNull?: boolean;
	hasDefault?: boolean;
}

function buildMetaField(spec: FieldSpec): MetaField {
	return {
		name: spec.name,
		isNotNull: spec.isNotNull ?? false,
		hasDefault: spec.hasDefault ?? false,
		type: {
			gqlType: spec.gqlType,
			isArray: spec.isArray ?? false,
			pgType: spec.pgType ?? 'text',
			pgAlias: spec.pgAlias ?? null,
			isNotNull: spec.isNotNull ?? false,
			hasDefault: spec.hasDefault ?? false,
			subtype: spec.subtype ?? null
		}
	} as MetaField;
}

interface TableSpec {
	name: string;
	fields: FieldSpec[];
	belongsTo?: Array<{ fieldName: string; references: string; keyName: string }>;
}

function camelPlural(name: string): string {
	// The mock adapter is keyed on table.name only; inflection names are cosmetic for these
	// fixtures, so a naive pluralization is sufficient.
	return name.endsWith('s') ? name : `${name}s`;
}

function buildMetaTable(spec: TableSpec): MetaTable {
	return {
		name: spec.name,
		schemaName: 'public',
		query: {
			all: camelPlural(spec.name),
			create: `create${cap(spec.name)}`,
			delete: `delete${cap(spec.name)}`,
			one: spec.name,
			update: `update${cap(spec.name)}`
		},
		fields: spec.fields.map(buildMetaField),
		inflection: {
			allRows: camelPlural(spec.name),
			connection: camelPlural(spec.name),
			tableType: spec.name
		},
		indexes: [],
		constraints: { primaryKey: null, unique: [], foreignKey: [] },
		foreignKeyConstraints: [],
		primaryKeyConstraints: [],
		uniqueConstraints: [],
		relations: {
			belongsTo: (spec.belongsTo ?? []).map((rel) => ({
				fieldName: rel.fieldName,
				isUnique: false,
				type: 'belongsTo',
				keys: [{ name: rel.keyName, type: { gqlType: 'UUID', isArray: false, pgType: 'uuid' } }],
				references: { name: rel.references }
			})),
			has: [],
			hasOne: [],
			hasMany: [],
			manyToMany: []
		}
	} as unknown as MetaTable;
}

function cap(s: string): string {
	return s.charAt(0).toUpperCase() + s.slice(1);
}

// ─── All-cell-types fixture: one column per forceable CellType ────────────────────────────────
// Ordered to match the CellType union (cell-types/types.ts). `id` stays a UUID so the readonly
// rule fires; every other column forces its type via pgAlias. `unknown` is the implicit fallback
// of resolveCellType (an unmapped type degrades to 'text'), so it has no dedicated forced column.
const ALL_CELL_TYPE_FIELDS: FieldSpec[] = [
	{ name: 'id', gqlType: 'UUID', pgAlias: 'uuid', pgType: 'uuid', isNotNull: true },
	// Text-based
	{ name: 'text', gqlType: 'String', pgAlias: 'text' },
	{ name: 'textarea', gqlType: 'String', pgAlias: 'textarea' },
	{ name: 'email', gqlType: 'String', pgAlias: 'email' },
	{ name: 'url', gqlType: 'String', pgAlias: 'url' },
	{ name: 'phone', gqlType: 'String', pgAlias: 'phone' },
	{ name: 'citext', gqlType: 'String', pgAlias: 'citext', pgType: 'citext' },
	{ name: 'bpchar', gqlType: 'String', pgAlias: 'bpchar', pgType: 'bpchar' },
	// Numeric
	{ name: 'number', gqlType: 'Float', pgAlias: 'number', pgType: 'float8' },
	{ name: 'integer', gqlType: 'Int', pgAlias: 'integer', pgType: 'int4' },
	{ name: 'smallint', gqlType: 'Int', pgAlias: 'smallint', pgType: 'int2' },
	{ name: 'decimal', gqlType: 'BigFloat', pgAlias: 'decimal', pgType: 'numeric' },
	{ name: 'currency', gqlType: 'Float', pgAlias: 'currency', pgType: 'money' },
	{ name: 'percentage', gqlType: 'Float', pgAlias: 'percentage' },
	// Date / time
	{ name: 'date', gqlType: 'Date', pgAlias: 'date', pgType: 'date' },
	{ name: 'datetime', gqlType: 'Datetime', pgAlias: 'datetime', pgType: 'timestamp' },
	{ name: 'time', gqlType: 'Time', pgAlias: 'time', pgType: 'time' },
	{ name: 'timestamptz', gqlType: 'Datetime', pgAlias: 'timestamptz', pgType: 'timestamptz' },
	{ name: 'interval', gqlType: 'Interval', pgAlias: 'interval', pgType: 'interval' },
	// Boolean
	{ name: 'boolean', gqlType: 'Boolean', pgAlias: 'boolean', pgType: 'bool' },
	{ name: 'toggle', gqlType: 'Boolean', pgAlias: 'toggle' },
	{ name: 'bit', gqlType: 'String', pgAlias: 'bit', pgType: 'bit' },
	// Structured
	{ name: 'json', gqlType: 'JSON', pgAlias: 'json', pgType: 'json' },
	{ name: 'jsonb', gqlType: 'JSON', pgAlias: 'jsonb', pgType: 'jsonb' },
	{ name: 'array', gqlType: 'String', pgAlias: 'array', isArray: true },
	// Typed arrays
	{ name: 'textArray', gqlType: 'String', pgAlias: 'text-array', isArray: true },
	{ name: 'uuidArray', gqlType: 'UUID', pgAlias: 'uuid-array', isArray: true },
	{ name: 'numberArray', gqlType: 'BigFloat', pgAlias: 'number-array', isArray: true },
	{ name: 'integerArray', gqlType: 'Int', pgAlias: 'integer-array', isArray: true },
	{ name: 'dateArray', gqlType: 'Date', pgAlias: 'date-array', isArray: true },
	// Geometry
	{ name: 'geometry', gqlType: 'GeoJSON', pgAlias: 'geometry', pgType: 'geometry' },
	{ name: 'geometryPoint', gqlType: 'GeoJSON', pgAlias: 'geometry-point', subtype: 'GeometryPoint' },
	{ name: 'geometryCollection', gqlType: 'GeometryGeometryCollection', pgAlias: 'geometry-collection' },
	// Network
	{ name: 'inet', gqlType: 'String', pgAlias: 'inet', pgType: 'inet' },
	// Media
	{ name: 'image', gqlType: 'String', pgAlias: 'image' },
	{ name: 'file', gqlType: 'JSON', pgAlias: 'file' },
	{ name: 'video', gqlType: 'String', pgAlias: 'video' },
	{ name: 'audio', gqlType: 'String', pgAlias: 'audio' },
	{ name: 'upload', gqlType: 'JSON', pgAlias: 'upload' },
	// Special
	{ name: 'uuid', gqlType: 'UUID', pgAlias: 'uuid', pgType: 'uuid' },
	{ name: 'color', gqlType: 'String', pgAlias: 'color' },
	{ name: 'rating', gqlType: 'Int', pgAlias: 'rating' },
	{ name: 'tags', gqlType: 'String', pgAlias: 'tags' },
	{ name: 'tsvector', gqlType: 'String', pgAlias: 'tsvector', pgType: 'tsvector' },
	{ name: 'origin', gqlType: 'String', pgAlias: 'origin' },
	// Relation (display-only here — value object carries displayName; RelationView reads it)
	{ name: 'relation', gqlType: 'JSON', pgAlias: 'relation' }
];

export function buildAllCellTypesTable(): MetaTable {
	return buildMetaTable({ name: 'demo', fields: ALL_CELL_TYPE_FIELDS });
}

// ─── Simple fixture: a few common columns for focused stories ─────────────────────────────────
const SIMPLE_FIELDS: FieldSpec[] = [
	{ name: 'id', gqlType: 'UUID', pgAlias: 'uuid', pgType: 'uuid', isNotNull: true },
	{ name: 'name', gqlType: 'String', pgAlias: 'text' },
	{ name: 'email', gqlType: 'String', pgAlias: 'email' },
	{ name: 'age', gqlType: 'Int', pgAlias: 'integer' },
	{ name: 'isActive', gqlType: 'Boolean', pgAlias: 'boolean', pgType: 'bool' },
	{ name: 'createdAt', gqlType: 'Datetime', pgAlias: 'timestamptz', pgType: 'timestamptz' }
];

export function buildSimpleTable(name = 'people'): MetaTable {
	return buildMetaTable({ name, fields: SIMPLE_FIELDS });
}

// ─── Relation fixture: a posts table with a real belongsTo → authors + an authors table ───────
export function buildRelationTables(): { posts: MetaTable; authors: MetaTable } {
	const authors = buildMetaTable({
		name: 'authors',
		fields: [
			{ name: 'id', gqlType: 'UUID', pgAlias: 'uuid', pgType: 'uuid', isNotNull: true },
			{ name: 'displayName', gqlType: 'String', pgAlias: 'text' },
			{ name: 'email', gqlType: 'String', pgAlias: 'email' }
		]
	});
	const posts = buildMetaTable({
		name: 'posts',
		fields: [
			{ name: 'id', gqlType: 'UUID', pgAlias: 'uuid', pgType: 'uuid', isNotNull: true },
			{ name: 'title', gqlType: 'String', pgAlias: 'text' },
			{ name: 'author', gqlType: 'JSON', pgAlias: 'relation' },
			{ name: 'authorId', gqlType: 'UUID', pgAlias: 'uuid', pgType: 'uuid' },
			{ name: 'publishedAt', gqlType: 'Datetime', pgAlias: 'timestamptz', pgType: 'timestamptz' }
		],
		belongsTo: [{ fieldName: 'author', references: 'authors', keyName: 'authorId' }]
	});
	return { posts, authors };
}

// ─── Deterministic value generators (per column type, seeded) ─────────────────────────────────

const WORDS = ['alpha', 'bravo', 'charlie', 'delta', 'echo', 'foxtrot', 'golf', 'hotel', 'india', 'juliet'];
const FIRST = ['Ada', 'Alan', 'Grace', 'Linus', 'Margaret', 'Dennis', 'Barbara', 'Ken', 'Edsger', 'Donald'];
const LAST = ['Lovelace', 'Turing', 'Hopper', 'Torvalds', 'Hamilton', 'Ritchie', 'Liskov', 'Thompson', 'Dijkstra', 'Knuth'];

function pick<T>(rng: () => number, arr: T[]): T {
	return arr[Math.floor(rng() * arr.length)];
}

function uuidLike(rng: () => number): string {
	const hex = () => Math.floor(rng() * 16).toString(16);
	const block = (n: number) => Array.from({ length: n }, hex).join('');
	return `${block(8)}-${block(4)}-4${block(3)}-${block(4)}-${block(12)}`;
}

function isoDate(rng: () => number): string {
	const year = 2020 + Math.floor(rng() * 6);
	const month = String(1 + Math.floor(rng() * 12)).padStart(2, '0');
	const day = String(1 + Math.floor(rng() * 28)).padStart(2, '0');
	return `${year}-${month}-${day}`;
}

function isoDateTime(rng: () => number): string {
	const hh = String(Math.floor(rng() * 24)).padStart(2, '0');
	const mm = String(Math.floor(rng() * 60)).padStart(2, '0');
	return `${isoDate(rng)}T${hh}:${mm}:00Z`;
}

const COLORS = ['#3b82f6', '#ef4444', '#22c55e', '#f59e0b', '#a855f7', '#06b6d4'];

// Self-contained data-URI SVG so image/file/video/audio/upload cells render a real
// thumbnail in stories (no backend / no network) instead of a broken-image glyph. The
// fill + label vary by type and row so the media columns are visually distinct + testable.
function placeholderMedia(bg: string, label: string): string {
	const svg = `<svg xmlns='http://www.w3.org/2000/svg' width='96' height='96'><rect width='96' height='96' fill='${bg}'/><text x='48' y='54' font-family='system-ui,sans-serif' font-size='13' font-weight='700' fill='white' text-anchor='middle'>${label}</text></svg>`;
	return `data:image/svg+xml,${encodeURIComponent(svg)}`;
}

// Generate one cell value appropriate to the (forced) CellType, keyed off the column name +
// metadata. Mirrors display-cases.ts representative values so each view paints a realistic cell.
function valueForField(spec: FieldSpec, rng: () => number, rowIndex: number): unknown {
	const alias = spec.pgAlias;
	const name = spec.name;

	if (name === 'id') return uuidLike(rng);

	if (spec.isArray) {
		switch (alias) {
			case 'uuid-array':
				return [uuidLike(rng), uuidLike(rng)];
			case 'number-array':
				return [Number((rng() * 100).toFixed(2)), Number((rng() * 100).toFixed(2))];
			case 'integer-array':
				return [Math.floor(rng() * 100), Math.floor(rng() * 100)];
			case 'date-array':
				return [isoDate(rng), isoDate(rng)];
			default:
				return [pick(rng, WORDS), pick(rng, WORDS), pick(rng, WORDS)];
		}
	}

	switch (alias) {
		case 'text':
			return `${pick(rng, WORDS)} ${pick(rng, WORDS)}`;
		case 'textarea':
			return `${pick(rng, WORDS)}\n${pick(rng, WORDS)} ${pick(rng, WORDS)}`;
		case 'email':
			return `${pick(rng, FIRST).toLowerCase()}.${pick(rng, LAST).toLowerCase()}@example.com`;
		case 'url':
			return `https://example.com/${pick(rng, WORDS)}/${rowIndex}.html`;
		// `pick(rng, COLORS)` consumes one rng() — same as the old url's `pick(rng, WORDS)` —
		// so non-media columns keep identical seeded values (golden stays minimal).
		case 'image':
			return placeholderMedia(pick(rng, COLORS), 'IMG');
		case 'video':
			return placeholderMedia(pick(rng, COLORS), 'VIDEO');
		case 'audio':
			return placeholderMedia(pick(rng, COLORS), 'AUDIO');
		case 'phone':
			return `+1 555 ${String(1000 + Math.floor(rng() * 8999))}`;
		case 'citext':
			return `${cap(pick(rng, WORDS))}Case`;
		case 'bpchar':
			return `${pick(rng, WORDS).slice(0, 2).toUpperCase()} `;
		case 'number':
			return Number((rng() * 1000).toFixed(2));
		case 'integer':
			return Math.floor(rng() * 1000);
		case 'smallint':
			return Math.floor(rng() * 100);
		case 'decimal':
			return (rng() * 1000).toFixed(2);
		case 'currency':
			return Number((rng() * 5000).toFixed(2));
		case 'percentage':
			return Number(rng().toFixed(2));
		case 'date':
			return isoDate(rng);
		case 'datetime':
		case 'timestamptz':
			return isoDateTime(rng);
		case 'time':
			return `${String(Math.floor(rng() * 24)).padStart(2, '0')}:${String(Math.floor(rng() * 60)).padStart(2, '0')}:00`;
		case 'interval':
			return { years: Math.floor(rng() * 3), months: Math.floor(rng() * 12), days: Math.floor(rng() * 28) };
		case 'boolean':
		case 'toggle':
			return rng() > 0.5;
		case 'bit':
			return rng() > 0.5 ? '1' : '0';
		case 'json':
			return { key: pick(rng, WORDS), n: Math.floor(rng() * 100), ok: rng() > 0.5 };
		case 'jsonb':
			return { nested: { items: [Math.floor(rng() * 10), Math.floor(rng() * 10)] }, tag: pick(rng, WORDS) };
		case 'geometry':
			return { type: 'Point', coordinates: [Number((rng() * 180 - 90).toFixed(4)), Number((rng() * 180 - 90).toFixed(4))] };
		case 'geometry-point':
			return { x: Number((rng() * 100).toFixed(2)), y: Number((rng() * 100).toFixed(2)) };
		case 'geometry-collection':
			return { type: 'GeometryCollection', geometries: [] };
		case 'inet':
			return `${Math.floor(rng() * 256)}.${Math.floor(rng() * 256)}.${Math.floor(rng() * 256)}.${Math.floor(rng() * 256)}`;
		case 'file':
			return { url: placeholderMedia(COLORS[rowIndex % COLORS.length], 'FILE'), name: `${pick(rng, WORDS)}.pdf` };
		case 'upload':
			return { url: placeholderMedia(COLORS[rowIndex % COLORS.length], 'UPLOAD'), path: `/uploads/${pick(rng, WORDS)}-${rowIndex}.bin` };
		case 'uuid':
			return uuidLike(rng);
		case 'color':
			return pick(rng, COLORS);
		case 'rating':
			return 1 + Math.floor(rng() * 5);
		case 'tags':
			return [pick(rng, WORDS), pick(rng, WORDS)].join(', ');
		case 'tsvector':
			return `'${pick(rng, WORDS)}':1A '${pick(rng, WORDS)}':2B`;
		case 'origin':
			return pick(rng, ['system', 'import', 'manual', 'api']);
		case 'relation':
			return { id: uuidLike(rng), displayName: `${pick(rng, FIRST)} ${pick(rng, LAST)}` };
		default:
			return `${pick(rng, WORDS)}-${rowIndex}`;
	}
}

/**
 * Deterministically generate `count` rows for a table built by the builders above.
 * The same (table fields, seed, count) always yields byte-identical rows.
 */
export function makeRows(table: MetaTable, count: number, seed = 1): SheetsRow[] {
	const rng = mulberry32(seed);
	const fields = (table.fields ?? []).filter((f): f is MetaField => f != null);
	// Reconstruct the FieldSpec view the generator needs (name + pgAlias + isArray) from meta.
	const specs: FieldSpec[] = fields.map((f) => ({
		name: f.name,
		gqlType: f.type.gqlType,
		pgAlias: f.type.pgAlias ?? undefined,
		isArray: f.type.isArray,
		subtype: f.type.subtype
	}));

	const rows: SheetsRow[] = [];
	for (let i = 0; i < count; i++) {
		const row: SheetsRow = {};
		for (const spec of specs) {
			row[spec.name] = valueForField(spec, rng, i);
		}
		// Guarantee a unique, stable id even if the table has no explicit id field.
		if (row.id == null) row.id = uuidLike(rng);
		rows.push(row);
	}
	return rows;
}

/** Convenience: an all-cell-types table + a matching small dataset. */
export function buildAllCellTypesFixture(rowCount = 25, seed = 7): { table: MetaTable; rows: SheetsRow[] } {
	const table = buildAllCellTypesTable();
	return { table, rows: makeRows(table, rowCount, seed) };
}
