/**
 * PHASE-0 GOLDEN — resolveCellType() schema-metadata -> cell-type pipeline.
 *
 * Pure data, no glide. Snapshots the CURRENT v1 behavior of
 * `resolveCellType(fieldName, fieldMeta)` for ~80 cases that exercise every
 * reachable branch of the resolution pipeline:
 *
 *   resolveCellType
 *     -> READONLY_CONDITIONS  (id+UUID / createdAt / updatedAt)
 *     -> CellRegistry.findByMatch  (the runtime singleton is EMPTY at module
 *        load — nothing registers entries — so this ALWAYS returns undefined and
 *        the resolver ALWAYS falls through to mapToFrontendCellType. Captured
 *        as-is; see `deviations`.)
 *     -> mapToFrontendCellType  (pgAlias > isArray > pgType > gqlType)
 *     -> canEdit / canActivate / activationBehavior  (NON_EDITABLE_TYPES +
 *        VIEWER_ONLY_TYPES = {tsvector}; SINGLE_CLICK_CELL_TYPES is EMPTY so
 *        activationBehavior is ALWAYS 'double-click').
 *
 * The golden is generated by the REAL resolver (UPDATE_GOLDEN=1), not by any
 * hand-predicted table, so it freezes actual behavior including bugs.
 */

import { describe, expect, it } from 'vitest';

import type { FieldMetadata } from '../../cell-types/cell-type-resolver';
import { resolveCellType } from '../../cell-types/cell-type-resolver';

import { assertOrUpdateGolden } from './parity.harness';

type FieldType = FieldMetadata['type'];

interface ResolverCase {
	label: string;
	fieldName: string;
	fieldMeta?: FieldMetadata;
}

/** Build a nested FieldMetadata for an ordinary (non-readonly) column name. */
function meta(type: FieldType): FieldMetadata {
	return { name: 'col', type };
}

// ─── Case table — ~80 cases, grouped by which branch they exercise ──────────

const CASES: ResolverCase[] = [
	// ── (A) gqlType fallback — every scalar branch of mapGraphQLTypeToCellType
	{ label: 'gql String -> text', fieldName: 'name', fieldMeta: meta({ gqlType: 'String' }) },
	{ label: 'gql Int -> integer', fieldName: 'count', fieldMeta: meta({ gqlType: 'Int' }) },
	{ label: 'gql Float -> number', fieldName: 'ratio', fieldMeta: meta({ gqlType: 'Float' }) },
	{ label: 'gql Boolean -> boolean', fieldName: 'active', fieldMeta: meta({ gqlType: 'Boolean' }) },
	{ label: 'gql ID -> uuid', fieldName: 'ref', fieldMeta: meta({ gqlType: 'ID' }) },
	{ label: 'gql DateTime -> datetime', fieldName: 'at', fieldMeta: meta({ gqlType: 'DateTime' }) },
	{ label: 'gql Datetime -> datetime', fieldName: 'at2', fieldMeta: meta({ gqlType: 'Datetime' }) },
	{ label: 'gql Date -> date', fieldName: 'day', fieldMeta: meta({ gqlType: 'Date' }) },
	{ label: 'gql Time -> time', fieldName: 'clock', fieldMeta: meta({ gqlType: 'Time' }) },
	{ label: 'gql JSON -> json', fieldName: 'blob', fieldMeta: meta({ gqlType: 'JSON' }) },
	{ label: 'gql JSONObject -> json', fieldName: 'obj', fieldMeta: meta({ gqlType: 'JSONObject' }) },
	{ label: 'gql Upload -> file', fieldName: 'doc', fieldMeta: meta({ gqlType: 'Upload' }) },
	{ label: 'gql URL -> url', fieldName: 'link', fieldMeta: meta({ gqlType: 'URL' }) },
	{ label: 'gql EmailAddress -> email', fieldName: 'mail', fieldMeta: meta({ gqlType: 'EmailAddress' }) },
	{ label: 'gql PhoneNumber -> phone', fieldName: 'tel', fieldMeta: meta({ gqlType: 'PhoneNumber' }) },
	{ label: 'gql UUID -> uuid', fieldName: 'guid', fieldMeta: meta({ gqlType: 'UUID' }) },
	{ label: 'gql BigFloat -> number', fieldName: 'big', fieldMeta: meta({ gqlType: 'BigFloat' }) },
	{ label: 'gql BigInt -> integer', fieldName: 'bigi', fieldMeta: meta({ gqlType: 'BigInt' }) },
	{ label: 'gql Relation -> relation', fieldName: 'owner', fieldMeta: meta({ gqlType: 'Relation' }) },
	{ label: 'gql Interval -> interval', fieldName: 'dur', fieldMeta: meta({ gqlType: 'Interval' }) },
	{
		label: 'gql GeometryGeometryCollection -> geometry-collection',
		fieldName: 'shapes',
		fieldMeta: meta({ gqlType: 'GeometryGeometryCollection' }),
	},
	{ label: 'gql unknown -> text (default)', fieldName: 'weird', fieldMeta: meta({ gqlType: 'Mystery' }) },
	{ label: 'gql non-null String! -> text (modifier stripped)', fieldName: 'req', fieldMeta: meta({ gqlType: 'String!' }) },
	{ label: 'gql empty string -> text', fieldName: 'empty', fieldMeta: meta({ gqlType: '' }) },

	// ── (B) GeoJSON subtype branches
	{ label: 'GeoJSON GeometryPoint -> geometry-point', fieldName: 'pt', fieldMeta: meta({ gqlType: 'GeoJSON', subtype: 'GeometryPoint' }) },
	{ label: 'GeoJSON GeometryPolygon -> geometry-collection', fieldName: 'poly', fieldMeta: meta({ gqlType: 'GeoJSON', subtype: 'GeometryPolygon' }) },
	{ label: 'GeoJSON default -> geometry', fieldName: 'geo', fieldMeta: meta({ gqlType: 'GeoJSON' }) },
	{ label: 'GeoJSON unrecognized subtype -> geometry', fieldName: 'geo2', fieldMeta: meta({ gqlType: 'GeoJSON', subtype: 'GeometryLine' }) },

	// ── (C) pgAlias branch — every alias key (priority 1, even over arrays)
	{ label: 'alias image -> image', fieldName: 'pic', fieldMeta: meta({ gqlType: 'JSON', pgAlias: 'image' }) },
	{ label: 'alias file -> file', fieldName: 'att', fieldMeta: meta({ gqlType: 'JSON', pgAlias: 'file' }) },
	{ label: 'alias video -> video', fieldName: 'clip', fieldMeta: meta({ gqlType: 'JSON', pgAlias: 'video' }) },
	{ label: 'alias audio -> audio', fieldName: 'snd', fieldMeta: meta({ gqlType: 'JSON', pgAlias: 'audio' }) },
	{ label: 'alias upload -> upload', fieldName: 'up', fieldMeta: meta({ gqlType: 'JSON', pgAlias: 'upload' }) },
	{ label: 'alias relation -> relation', fieldName: 'rel', fieldMeta: meta({ gqlType: 'String', pgAlias: 'relation' }) },
	{ label: 'alias email -> email', fieldName: 'em', fieldMeta: meta({ gqlType: 'String', pgAlias: 'email' }) },
	{ label: 'alias url -> url', fieldName: 'u', fieldMeta: meta({ gqlType: 'String', pgAlias: 'url' }) },
	{ label: 'alias phone -> phone', fieldName: 'ph', fieldMeta: meta({ gqlType: 'String', pgAlias: 'phone' }) },
	{ label: 'alias citext -> citext', fieldName: 'ci', fieldMeta: meta({ gqlType: 'String', pgAlias: 'citext' }) },
	{ label: 'alias textarea -> textarea', fieldName: 'ta', fieldMeta: meta({ gqlType: 'String', pgAlias: 'textarea' }) },
	{ label: 'alias number -> number', fieldName: 'n', fieldMeta: meta({ gqlType: 'Float', pgAlias: 'number' }) },
	{ label: 'alias currency -> currency', fieldName: 'price', fieldMeta: meta({ gqlType: 'Float', pgAlias: 'currency' }) },
	{ label: 'alias percentage -> percentage', fieldName: 'pct', fieldMeta: meta({ gqlType: 'Float', pgAlias: 'percentage' }) },
	{ label: 'alias numeric -> decimal', fieldName: 'num', fieldMeta: meta({ gqlType: 'Float', pgAlias: 'numeric' }) },
	{ label: 'alias decimal -> decimal', fieldName: 'dec', fieldMeta: meta({ gqlType: 'Float', pgAlias: 'decimal' }) },
	{ label: 'alias int -> integer', fieldName: 'i', fieldMeta: meta({ gqlType: 'Int', pgAlias: 'int' }) },
	{ label: 'alias integer -> integer', fieldName: 'i2', fieldMeta: meta({ gqlType: 'Int', pgAlias: 'integer' }) },
	{ label: 'alias smallint -> smallint', fieldName: 'si', fieldMeta: meta({ gqlType: 'Int', pgAlias: 'smallint' }) },
	{ label: 'alias boolean -> boolean', fieldName: 'b', fieldMeta: meta({ gqlType: 'Boolean', pgAlias: 'boolean' }) },
	{ label: 'alias toggle -> toggle', fieldName: 'tg', fieldMeta: meta({ gqlType: 'Boolean', pgAlias: 'toggle' }) },
	{ label: 'alias date -> date', fieldName: 'd', fieldMeta: meta({ gqlType: 'Date', pgAlias: 'date' }) },
	{ label: 'alias datetime -> datetime', fieldName: 'dt', fieldMeta: meta({ gqlType: 'DateTime', pgAlias: 'datetime' }) },
	{ label: 'alias time -> time', fieldName: 't', fieldMeta: meta({ gqlType: 'Time', pgAlias: 'time' }) },
	{ label: 'alias timestamptz -> timestamptz', fieldName: 'tstz', fieldMeta: meta({ gqlType: 'DateTime', pgAlias: 'timestamptz' }) },
	{ label: 'alias interval -> interval', fieldName: 'iv', fieldMeta: meta({ gqlType: 'Interval', pgAlias: 'interval' }) },
	{ label: 'alias json -> json', fieldName: 'j', fieldMeta: meta({ gqlType: 'JSON', pgAlias: 'json' }) },
	{ label: 'alias jsonb -> jsonb', fieldName: 'jb', fieldMeta: meta({ gqlType: 'JSON', pgAlias: 'jsonb' }) },
	{ label: 'alias inet -> inet', fieldName: 'ip', fieldMeta: meta({ gqlType: 'String', pgAlias: 'inet' }) },
	{ label: 'alias geometry -> geometry', fieldName: 'g', fieldMeta: meta({ gqlType: 'GeoJSON', pgAlias: 'geometry' }) },
	{ label: 'alias geometry-point -> geometry-point', fieldName: 'gp', fieldMeta: meta({ gqlType: 'GeoJSON', pgAlias: 'geometry-point' }) },
	{ label: 'alias geometry-collection -> geometry-collection', fieldName: 'gc', fieldMeta: meta({ gqlType: 'GeoJSON', pgAlias: 'geometry-collection' }) },
	{ label: 'alias color -> color', fieldName: 'c', fieldMeta: meta({ gqlType: 'String', pgAlias: 'color' }) },
	{ label: 'alias rating -> rating', fieldName: 'r', fieldMeta: meta({ gqlType: 'Int', pgAlias: 'rating' }) },
	{ label: 'alias tags -> tags', fieldName: 'tg2', fieldMeta: meta({ gqlType: 'String', pgAlias: 'tags' }) },
	{ label: 'alias uuid -> uuid', fieldName: 'uu', fieldMeta: meta({ gqlType: 'UUID', pgAlias: 'uuid' }) },
	{ label: 'alias tsvector -> tsvector (NON_EDITABLE + VIEWER_ONLY)', fieldName: 'search', fieldMeta: meta({ gqlType: 'String', pgAlias: 'tsvector' }) },
	{ label: 'alias origin -> origin', fieldName: 'og', fieldMeta: meta({ gqlType: 'String', pgAlias: 'origin' }) },
	{ label: 'alias char -> bpchar', fieldName: 'ch', fieldMeta: meta({ gqlType: 'String', pgAlias: 'char' }) },
	{ label: 'alias bpchar -> bpchar', fieldName: 'bp', fieldMeta: meta({ gqlType: 'String', pgAlias: 'bpchar' }) },
	{ label: 'alias text -> text', fieldName: 'tx', fieldMeta: meta({ gqlType: 'String', pgAlias: 'text' }) },
	{ label: 'alias bit -> bit', fieldName: 'bt', fieldMeta: meta({ gqlType: 'String', pgAlias: 'bit' }) },
	{ label: 'alias UPPERCASE IMAGE -> image (case-insensitive)', fieldName: 'pic2', fieldMeta: meta({ gqlType: 'JSON', pgAlias: 'IMAGE' }) },
	{ label: 'alias unknown -> falls through to gqlType', fieldName: 'fall', fieldMeta: meta({ gqlType: 'Int', pgAlias: 'zzz-not-real' }) },
	{ label: 'alias unknown -> falls through to pgType', fieldName: 'fall2', fieldMeta: meta({ gqlType: 'String', pgAlias: 'zzz', pgType: 'uuid' }) },

	// ── (D) pgAlias array keys (priority 1 beats the isArray branch)
	{ label: 'alias array -> array', fieldName: 'arr', fieldMeta: meta({ gqlType: 'String', isArray: true, pgAlias: 'array' }) },
	{ label: 'alias text-array -> text-array', fieldName: 'ta_arr', fieldMeta: meta({ gqlType: 'String', isArray: true, pgAlias: 'text-array' }) },
	{ label: 'alias integer-array -> integer-array', fieldName: 'i_arr', fieldMeta: meta({ gqlType: 'Int', isArray: true, pgAlias: 'integer-array' }) },
	{ label: 'alias number-array -> number-array', fieldName: 'n_arr', fieldMeta: meta({ gqlType: 'BigFloat', isArray: true, pgAlias: 'number-array' }) },
	{ label: 'alias uuid-array -> uuid-array', fieldName: 'u_arr', fieldMeta: meta({ gqlType: 'UUID', isArray: true, pgAlias: 'uuid-array' }) },
	{ label: 'alias date-array -> date-array', fieldName: 'd_arr', fieldMeta: meta({ gqlType: 'Date', isArray: true, pgAlias: 'date-array' }) },
	{ label: 'alias image WINS over isArray -> image', fieldName: 'pics', fieldMeta: meta({ gqlType: 'String', isArray: true, pgAlias: 'image' }) },

	// ── (E) isArray branch (no pgAlias) — arrayTypeMap + generic fallback
	{ label: 'array String -> text-array', fieldName: 'sarr', fieldMeta: meta({ gqlType: 'String', isArray: true }) },
	{ label: 'array UUID -> uuid-array', fieldName: 'uarr', fieldMeta: meta({ gqlType: 'UUID', isArray: true }) },
	{ label: 'array BigFloat -> number-array', fieldName: 'narr', fieldMeta: meta({ gqlType: 'BigFloat', isArray: true }) },
	{ label: 'array Int -> integer-array', fieldName: 'iarr', fieldMeta: meta({ gqlType: 'Int', isArray: true }) },
	{ label: 'array Date -> date-array', fieldName: 'darr', fieldMeta: meta({ gqlType: 'Date', isArray: true }) },
	{ label: 'array unknown base -> array (generic)', fieldName: 'garr', fieldMeta: meta({ gqlType: 'Foo', isArray: true }) },
	{ label: 'array bracket notation [String] -> text-array', fieldName: 'barr', fieldMeta: meta({ gqlType: '[String]', isArray: true }) },
	{ label: 'array bracket non-null [Int!]! -> integer-array', fieldName: 'barr2', fieldMeta: meta({ gqlType: '[Int!]!', isArray: true }) },

	// ── (F) pgType branch (no pgAlias, not array) — mapBackendTypeToCellType
	{ label: 'pgType varchar -> text', fieldName: 'vc', fieldMeta: meta({ gqlType: 'String', pgType: 'varchar' }) },
	{ label: 'pgType citext -> citext', fieldName: 'pgci', fieldMeta: meta({ gqlType: 'String', pgType: 'citext' }) },
	{ label: 'pgType bpchar -> bpchar', fieldName: 'pgbp', fieldMeta: meta({ gqlType: 'String', pgType: 'bpchar' }) },
	{ label: 'pgType int4 -> integer', fieldName: 'i4', fieldMeta: meta({ gqlType: 'Int', pgType: 'int4' }) },
	{ label: 'pgType int2 -> smallint', fieldName: 'i2pg', fieldMeta: meta({ gqlType: 'Int', pgType: 'int2' }) },
	{ label: 'pgType bigint -> integer', fieldName: 'bi', fieldMeta: meta({ gqlType: 'String', pgType: 'bigint' }) },
	{ label: 'pgType numeric -> decimal', fieldName: 'pgnum', fieldMeta: meta({ gqlType: 'String', pgType: 'numeric' }) },
	{ label: 'pgType real -> number', fieldName: 'rl', fieldMeta: meta({ gqlType: 'Float', pgType: 'real' }) },
	{ label: 'pgType double precision -> number', fieldName: 'dp', fieldMeta: meta({ gqlType: 'Float', pgType: 'double precision' }) },
	{ label: 'pgType money -> currency', fieldName: 'mny', fieldMeta: meta({ gqlType: 'String', pgType: 'money' }) },
	{ label: 'pgType bool -> boolean', fieldName: 'bl', fieldMeta: meta({ gqlType: 'Boolean', pgType: 'bool' }) },
	{ label: 'pgType bit varying -> bit', fieldName: 'bv', fieldMeta: meta({ gqlType: 'String', pgType: 'bit varying' }) },
	{ label: 'pgType timestamp -> datetime', fieldName: 'ts', fieldMeta: meta({ gqlType: 'String', pgType: 'timestamp' }) },
	{ label: 'pgType timestamptz -> timestamptz', fieldName: 'tstz2', fieldMeta: meta({ gqlType: 'String', pgType: 'timestamptz' }) },
	{ label: 'pgType timetz -> time', fieldName: 'ttz', fieldMeta: meta({ gqlType: 'String', pgType: 'timetz' }) },
	{ label: 'pgType interval -> interval', fieldName: 'ivpg', fieldMeta: meta({ gqlType: 'String', pgType: 'interval' }) },
	{ label: 'pgType jsonb -> jsonb', fieldName: 'jbpg', fieldMeta: meta({ gqlType: 'JSON', pgType: 'jsonb' }) },
	{ label: 'pgType uuid -> uuid', fieldName: 'uupg', fieldMeta: meta({ gqlType: 'String', pgType: 'uuid' }) },
	{ label: 'pgType tsvector -> tsvector (NON_EDITABLE)', fieldName: 'tsv', fieldMeta: meta({ gqlType: 'String', pgType: 'tsvector' }) },
	{ label: 'pgType cidr -> inet', fieldName: 'cidr', fieldMeta: meta({ gqlType: 'String', pgType: 'cidr' }) },
	{ label: 'pgType macaddr -> text', fieldName: 'mac', fieldMeta: meta({ gqlType: 'String', pgType: 'macaddr' }) },
	{ label: 'pgType point -> geometry-point', fieldName: 'ptpg', fieldMeta: meta({ gqlType: 'String', pgType: 'point' }) },
	{ label: 'pgType polygon -> geometry', fieldName: 'polypg', fieldMeta: meta({ gqlType: 'String', pgType: 'polygon' }) },
	{ label: 'pgType geography -> geometry', fieldName: 'geog', fieldMeta: meta({ gqlType: 'String', pgType: 'geography' }) },
	{ label: 'pgType email -> email', fieldName: 'empg', fieldMeta: meta({ gqlType: 'String', pgType: 'email' }) },
	{ label: 'pgType origin -> origin', fieldName: 'ogpg', fieldMeta: meta({ gqlType: 'String', pgType: 'origin' }) },
	{ label: 'pgType _text -> array', fieldName: 'txtarr', fieldMeta: meta({ gqlType: 'String', pgType: '_text' }) },
	{ label: 'pgType unknown -> falls through to gqlType', fieldName: 'pgfall', fieldMeta: meta({ gqlType: 'Boolean', pgType: 'zzz-not-real' }) },

	// ── (G) READONLY matrix
	{ label: 'readonly: id WITH gqlType UUID -> readonly uuid', fieldName: 'id', fieldMeta: meta({ gqlType: 'UUID' }) },
	{ label: 'readonly: id WITHOUT UUID (Int) -> NOT readonly integer', fieldName: 'id', fieldMeta: meta({ gqlType: 'Int' }) },
	{ label: 'readonly: id String -> NOT readonly text', fieldName: 'id', fieldMeta: meta({ gqlType: 'String' }) },
	{ label: 'readonly: id with NO fieldMeta -> NOT readonly, text', fieldName: 'id', fieldMeta: undefined },
	{ label: 'readonly: createdAt -> readonly (always)', fieldName: 'createdAt', fieldMeta: meta({ gqlType: 'DateTime' }) },
	{ label: 'readonly: createdAt with NO fieldMeta -> readonly text', fieldName: 'createdAt', fieldMeta: undefined },
	{ label: 'readonly: updatedAt -> readonly (always)', fieldName: 'updatedAt', fieldMeta: meta({ gqlType: 'DateTime' }) },
	{ label: 'editable: normal field -> NOT readonly', fieldName: 'title', fieldMeta: meta({ gqlType: 'String' }) },

	// ── (H) tsvector locks (NON_EDITABLE_TYPES + VIEWER_ONLY_TYPES) — canActivate true, canEdit false
	{ label: 'tsvector readonly-name interplay: updatedAt+tsvector', fieldName: 'updatedAt', fieldMeta: meta({ gqlType: 'String', pgType: 'tsvector' }) },

	// ── (I) undefined fieldMeta (and fieldMeta with no .type) -> default text
	{ label: 'undefined fieldMeta -> text default', fieldName: 'whatever', fieldMeta: undefined },
	{ label: 'fieldMeta present but no .type -> text default', fieldName: 'whatever2', fieldMeta: { name: 'whatever2' } },
];

describe('resolveCellType golden — schema-metadata -> cell-type pipeline', () => {
	const results = CASES.map((c) => ({
		label: c.label,
		fieldName: c.fieldName,
		fieldMeta: c.fieldMeta ?? null,
		resolution: resolveCellType(c.fieldName, c.fieldMeta),
	}));

	it('matches the committed golden', () => {
		assertOrUpdateGolden('resolver.golden', results);
	});

	it('every case has activationBehavior === double-click (locks the EMPTY single-click set)', () => {
		for (const r of results) {
			expect(r.resolution.activationBehavior, r.label).toBe('double-click');
		}
	});

	it('has at least ~80 cases', () => {
		expect(results.length).toBeGreaterThanOrEqual(80);
	});

	it('tsvector is non-editable but still activatable (viewer-only lock)', () => {
		// Reachable via alias and via pgType; both must lock the same way.
		for (const r of results.filter((x) => x.resolution.cellType === 'tsvector')) {
			expect(r.resolution.canEdit, `${r.label} canEdit`).toBe(false);
			// canActivate is canEdit || VIEWER_ONLY.has -> true, UNLESS a readonly
			// field-name ALSO forced canEdit false via isReadonly (still viewer-only).
			expect(r.resolution.canActivate, `${r.label} canActivate`).toBe(true);
		}
	});
});
