'use client';

/**
 * mfa-backup-codes-display  (registry: auth-mfa-backup-codes-display)
 *
 * Display-only card for one-time presentation of MFA backup codes. Codes are
 * passed in via the `codes` prop by the caller (auth-mfa-totp-enroll or
 * auth-mfa-backup-codes-regenerate); this block has NO generated-hook import,
 * NO fetch, NO network call, and NO requires.json — it is purely presentational
 * (sdk-binding-contract.md §7: presentational blocks ship no manifest).
 *
 * Affordances:
 *   • 2-column grid of monospace <code> cells (selectable, 1-col on mobile).
 *   • "Copy all" — writes all codes as newline-separated text to the clipboard.
 *   • "Download as .txt" — client-side download, one code per line + header.
 *   • "I have saved…" checkbox gate + "Continue" button (when requireConfirmation=true).
 *
 * Accessibility:
 *   • Codes rendered as <ul><li><code> for screen readers.
 *   • Copy/download buttons have aria-label.
 *   • Checkbox associated to label via htmlFor.
 *   • Continue button has aria-disabled="true" until checkbox is checked.
 *
 * NOTE: Backend generate_backup_codes procedure is future/undeployed. Codes are
 * generated by the CALLER and passed in here — see the `codes` prop.
 */

import { useState } from 'react';

import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@constructive-io/ui/card';
import { Button } from '@constructive-io/ui/button';
import { Checkbox } from '@constructive-io/ui/checkbox';
import { Badge } from '@constructive-io/ui/badge';

import { cn } from '@/lib/utils';

import {
  defaultMfaBackupCodesDisplayMessages,
  type MfaBackupCodesDisplayMessageOverrides
} from './messages';

export type MfaBackupCodesDisplayProps = {
  /** The backup codes to display. Returned from generate_backup_codes() by the caller. */
  codes: string[];
  /**
   * When true (default), renders an "I have saved these codes" checkbox gate.
   * The onConfirm callback fires only after the user checks the box and clicks Continue.
   */
  requireConfirmation?: boolean;
  /** Fires when user confirms they have saved the codes (clicks Continue). */
  onConfirm?: () => void;
  /** Notification seam — fires for the confirm event. Always fires when onConfirm is called. */
  onMessage?: (event: { kind: 'success' | 'error' | 'info' | 'warning'; key: string; message?: string }) => void;
  messages?: MfaBackupCodesDisplayMessageOverrides;
  className?: string;
};

export function MfaBackupCodesDisplay({
  codes,
  requireConfirmation = true,
  onConfirm,
  onMessage,
  messages: messageOverrides,
  className
}: MfaBackupCodesDisplayProps) {
  // Deep merge: top-level copy + the errors map merged separately.
  const merged = {
    ...defaultMfaBackupCodesDisplayMessages,
    ...messageOverrides,
    errors: {
      ...defaultMfaBackupCodesDisplayMessages.errors,
      ...messageOverrides?.errors
    }
  };

  const [copied, setCopied] = useState(false);
  const [confirmed, setConfirmed] = useState(false);

  function handleCopyAll() {
    const text = codes.join('\n');
    navigator.clipboard.writeText(text).then(() => {
      setCopied(true);
      // Reset the "Copied!" label after 2 seconds
      setTimeout(() => setCopied(false), 2000);
    });
  }

  function handleDownload() {
    const header = '# Backup codes for your account — keep these safe\n\n';
    const body = codes.join('\n');
    const blob = new Blob([header + body], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement('a');
    anchor.href = url;
    anchor.download = 'backup-codes.txt';
    anchor.click();
    URL.revokeObjectURL(url);
  }

  function handleContinue() {
    onMessage?.({ kind: 'success', key: 'backupCodes.confirmed' });
    onConfirm?.();
  }

  const continueDisabled = requireConfirmation && !confirmed;

  return (
    <Card data-slot="mfa-backup-codes-display" className={cn('w-full max-w-sm mx-auto', className)}>
      <CardHeader>
        <CardTitle>{merged.title}</CardTitle>
        <CardDescription>{merged.description}</CardDescription>
      </CardHeader>

      <CardContent className="space-y-5">
        {/* Warning badge — codes are shown once */}
        <div className="flex items-center gap-2 rounded-md bg-amber-50 border border-amber-200 px-3 py-2.5">
          <Badge variant="outline" className="shrink-0 text-amber-700 border-amber-300 bg-amber-100 text-xs">
            Warning
          </Badge>
          <p className="text-amber-800 text-sm leading-snug">{merged.warningText}</p>
        </div>

        {/* Code grid — 2 columns, 1 on mobile */}
        <ul
          aria-label="Backup codes"
          className="grid grid-cols-1 sm:grid-cols-2 gap-2 list-none m-0 p-0"
        >
          {codes.map((code, i) => (
            <li key={i} className="flex items-center justify-center">
              <code
                className={cn(
                  'block w-full text-center font-mono text-sm',
                  'rounded-md border border-border bg-muted px-3 py-2',
                  'select-text cursor-text tracking-wider'
                )}
              >
                {code}
              </code>
            </li>
          ))}
        </ul>

        {/* Copy all + Download actions */}
        <div className="flex gap-2">
          <Button
            type="button"
            variant="outline"
            size="sm"
            className="flex-1"
            aria-label={copied ? merged.copiedButton : merged.copyAllButton}
            onClick={handleCopyAll}
            data-testid="copy-all"
          >
            {copied ? merged.copiedButton : merged.copyAllButton}
          </Button>
          <Button
            type="button"
            variant="outline"
            size="sm"
            className="flex-1"
            aria-label={merged.downloadButton}
            onClick={handleDownload}
            data-testid="download"
          >
            {merged.downloadButton}
          </Button>
        </div>

        {/* Confirmation checkbox */}
        {requireConfirmation && (
          <div className="flex items-start space-x-2 pt-1">
            <Checkbox
              id="mfa-backup-confirmed"
              checked={confirmed}
              onCheckedChange={(checked) => setConfirmed(checked === true)}
              data-testid="confirm-checkbox"
            />
            <label
              htmlFor="mfa-backup-confirmed"
              className="text-sm leading-snug font-medium cursor-pointer select-none"
            >
              {merged.confirmCheckboxLabel}
            </label>
          </div>
        )}
      </CardContent>

      {/* Continue button in footer */}
      <CardFooter>
        <Button
          type="button"
          className="w-full"
          disabled={continueDisabled}
          aria-disabled={continueDisabled}
          onClick={handleContinue}
          data-testid="continue-button"
        >
          {merged.continueButton}
        </Button>
      </CardFooter>
    </Card>
  );
}
