import { defineConfig } from 'tsup';

// "use client" banner handling:
// We use onSuccess to run a post-build script that adds "use client" to all output files.
// This is necessary because:
// 1. tsup's `banner` option doesn't work with `treeshake: true` (rollup strips directives)
// 2. Both configs run in parallel, so both need onSuccess to handle race conditions
// 3. The script is idempotent - it skips files that already have the banner
// This ensures Next.js consumers can use these components without "use client" errors in dev mode.

export default defineConfig([
  // Main entry point - barrel export
  {
    entry: ['src/index.ts'],
    format: ['esm', 'cjs'],
    dts: true,
    sourcemap: true,
    clean: true,
    onSuccess: 'node scripts/add-use-client-banner.mjs',
    external: [
      'react',
      'react-dom',
      '@base-ui/react',
      '@internationalized/date',
      '@remixicon/react',
      '@use-gesture/react',
      '@xyflow/react',
      '@xyflow/system',
      'ace-builds',
      'cmdk',
      'lucide-react',
      'match-sorter',
      'motion',
      'react-ace',
      'react-aria-components',
      'react-hook-form',
      'react-resizable-panels',
      'sonner',
      'vaul',
    ],
    treeshake: true,
    splitting: false,
  },
  // Individual component entry points for tree-shaking
  {
    entry: {
      'components/button': 'src/components/button.tsx',
      'components/badge': 'src/components/badge.tsx',
      'components/label': 'src/components/label.tsx',
      'components/skeleton': 'src/components/skeleton.tsx',
      'components/card': 'src/components/card.tsx',
      'components/separator': 'src/components/separator.tsx',
      'components/alert': 'src/components/alert.tsx',
      'components/input': 'src/components/input.tsx',
      'components/textarea': 'src/components/textarea.tsx',
      'components/checkbox': 'src/components/checkbox.tsx',
      'components/checkbox-group': 'src/components/checkbox-group.tsx',
      'components/radio-group': 'src/components/radio-group.tsx',
      'components/switch': 'src/components/switch.tsx',
      'components/select': 'src/components/select.tsx',
      'components/progress': 'src/components/progress.tsx',
      'components/form': 'src/components/form.tsx',
      'components/form-control': 'src/components/form-control.tsx',
      'components/input-group': 'src/components/input-group.tsx',
      'components/field': 'src/components/field.tsx',
      'components/tooltip': 'src/components/tooltip.tsx',
      'components/popover': 'src/components/popover.tsx',
      'components/dialog': 'src/components/dialog.tsx',
      'components/alert-dialog': 'src/components/alert-dialog.tsx',
      'components/dropdown-menu': 'src/components/dropdown-menu.tsx',
      'components/sheet': 'src/components/sheet.tsx',
      'components/drawer': 'src/components/drawer.tsx',
      'components/tabs': 'src/components/tabs.tsx',
      'components/collapsible': 'src/components/collapsible.tsx',
      'components/scroll-area': 'src/components/scroll-area.tsx',
      'components/resizable': 'src/components/resizable.tsx',
      'components/table': 'src/components/table.tsx',
      'components/pagination': 'src/components/pagination.tsx',
      'components/breadcrumb': 'src/components/breadcrumb.tsx',
      'components/avatar': 'src/components/avatar.tsx',
      'components/autocomplete': 'src/components/autocomplete.tsx',
      'components/command': 'src/components/command.tsx',
      'components/combobox': 'src/components/combobox.tsx',
      'components/multi-select': 'src/components/multi-select.tsx',
      'components/tags': 'src/components/tags.tsx',
      'components/record-picker': 'src/components/record-picker.tsx',
      'components/stepper': 'src/components/stepper.tsx',
      'components/sidebar': 'src/components/sidebar.tsx',
      'components/calendar-rac': 'src/components/calendar-rac.tsx',
      'components/json-input': 'src/components/json-input.tsx',
      'components/sonner': 'src/components/sonner.tsx',
      'components/dock': 'src/components/dock.tsx',
      'components/page-header': 'src/components/page-header.tsx',
      'components/flickering-grid': 'src/components/flickering-grid.tsx',
      'components/motion-grid': 'src/components/motion-grid.tsx',
      'components/progressive-blur': 'src/components/progressive-blur.tsx',
      'components/progressive-blur-scroll-container': 'src/components/progressive-blur-scroll-container.tsx',
      'components/responsive-diagram': 'src/components/responsive-diagram.tsx',
      'components/portal': 'src/components/portal.tsx',
      'components/unlink-button': 'src/components/unlink-button.tsx',
      'components/stack/index': 'src/components/stack/index.ts',
      'components/toast/index': 'src/components/toast/index.ts',
      'components/org-chart/index': 'src/components/org-chart/index.ts',
      'components/storage/index': 'src/components/storage/index.ts',
    },
    format: ['esm', 'cjs'],
    dts: true,
    sourcemap: true,
    external: [
      'react',
      'react-dom',
      '@base-ui/react',
      '@internationalized/date',
      '@remixicon/react',
      '@use-gesture/react',
      '@xyflow/react',
      '@xyflow/system',
      'ace-builds',
      'cmdk',
      'lucide-react',
      'match-sorter',
      'motion',
      'react-ace',
      'react-aria-components',
      'react-hook-form',
      'react-resizable-panels',
      'sonner',
      'vaul',
    ],
    treeshake: true,
    splitting: false,
    onSuccess: 'node scripts/add-use-client-banner.mjs',
  },
]);
