import type { Integration, IntegrationTool } from './types';

function toolId(name: string) {
	return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}
const read = (name: string): IntegrationTool => ({ id: toolId(name), name, access: 'read' });
const write = (name: string): IntegrationTool => ({ id: toolId(name), name, access: 'write' });

type AppSeed = Omit<Integration, 'connected'> & { connected?: boolean };
const app = ({ connected = false, ...seed }: AppSeed): Integration => ({ ...seed, connected });

/** Demo app directory. Colors tint the monogram marks; hosts pass real brand marks via `mark`. */
export const DEMO_INTEGRATIONS: Integration[] = [
	app({
		id: 'claude',
		name: 'Claude',
		description: 'Send agent runs to Anthropic models',
		recommended: true,
		vendor: 'Anthropic',
		authDomain: 'console.anthropic.com',
		color: '#D97757',
		tools: [read('Complete a prompt'), write('Stream a reply')],
	}),
	app({
		id: 'gpt',
		name: 'GPT',
		description: 'Send agent runs to OpenAI models',
		recommended: true,
		vendor: 'OpenAI',
		authDomain: 'platform.openai.com',
		color: '#10A37F',
		tools: [read('Complete a prompt'), write('Stream a reply'), read('Create embeddings')],
	}),
	app({
		id: 'postgres',
		name: 'Postgres',
		description: 'Query your Constructive databases',
		categoryId: 'data',
		recommended: true,
		connected: true,
		vendor: 'Constructive',
		authDomain: 'constructive.io',
		color: '#336791',
		tools: [read('Run a read-only query'), read('Describe a table'), read('List schemas'), write('Apply a migration')],
	}),
	app({
		id: 'snowflake',
		name: 'Snowflake',
		description: 'Query the warehouse and read lineage',
		categoryId: 'data',
		recommended: true,
		connected: true,
		vendor: 'Snowflake',
		authDomain: 'app.snowflake.com',
		color: '#29B5E8',
		tools: [read('Run a query'), read('Describe a table'), read('Read query history')],
	}),
	app({
		id: 'bigquery',
		name: 'BigQuery',
		description: 'Query datasets and read job history',
		categoryId: 'data',
		vendor: 'Google',
		authDomain: 'accounts.google.com',
		color: '#4386FA',
		tools: [read('Run a query'), read('List datasets'), read('Read job history')],
	}),
	app({
		id: 'dbt',
		name: 'dbt',
		description: 'Read models, runs and tests',
		categoryId: 'data',
		connected: true,
		vendor: 'dbt Labs',
		authDomain: 'cloud.getdbt.com',
		color: '#FF694B',
		tools: [read('Read model runs'), read('Read test results'), read('Read lineage'), write('Trigger a job')],
	}),
	app({
		id: 'stripe',
		name: 'Stripe',
		description: 'Read subscriptions, invoices and refunds',
		categoryId: 'revenue',
		recommended: true,
		connected: true,
		vendor: 'Stripe',
		authDomain: 'dashboard.stripe.com',
		color: '#635BFF',
		tools: [read('List subscriptions'), read('Read invoices'), read('Read customers'), write('Issue a refund')],
	}),
	app({
		id: 'hubspot',
		name: 'HubSpot',
		description: 'Read deals, stages and owners',
		categoryId: 'revenue',
		recommended: true,
		vendor: 'HubSpot',
		authDomain: 'app.hubspot.com',
		color: '#FF7A59',
		tools: [read('Read deals'), read('Read companies'), read('Read deal stage history'), write('Update a deal')],
	}),
	app({
		id: 'salesforce',
		name: 'Salesforce',
		description: 'Read opportunities and accounts',
		categoryId: 'revenue',
		vendor: 'Salesforce',
		authDomain: 'login.salesforce.com',
		color: '#00A1E0',
		tools: [read('Read opportunities'), read('Read accounts'), write('Update an opportunity')],
	}),
	app({
		id: 'github',
		name: 'GitHub',
		description: 'Pull requests, checks and migrations',
		categoryId: 'code-ci',
		recommended: true,
		connected: true,
		vendor: 'GitHub',
		authDomain: 'github.com',
		tools: [read('List repositories'), read('Read a pull request'), read('Read check runs'), write('Leave a review comment'), write('File an issue')],
	}),
	app({
		id: 'vercel',
		name: 'Vercel',
		description: 'Deployments and build output',
		categoryId: 'code-ci',
		recommended: true,
		vendor: 'Vercel',
		authDomain: 'vercel.com',
		tools: [read('List deployments'), read('Read build output'), write('Promote a deployment')],
	}),
	app({
		id: 'slack',
		name: 'Slack',
		description: 'Channels, threads and posts',
		categoryId: 'communication',
		recommended: true,
		connected: true,
		vendor: 'Slack',
		authDomain: 'slack.com',
		color: '#611F69',
		tools: [read('Read channel history'), read('Read a thread'), write('Post a message'), write('Reply in a thread')],
	}),
	app({
		id: 'notion',
		name: 'Notion',
		description: 'Pages, databases and filing',
		categoryId: 'docs',
		recommended: true,
		connected: true,
		vendor: 'Notion',
		authDomain: 'notion.so',
		tools: [read('Search the workspace'), read('Query a database'), write('Create a page'), write('Append to a page')],
	}),
	app({
		id: 'gitlab',
		name: 'GitLab',
		description: 'Merge requests and pipelines',
		categoryId: 'code-ci',
		vendor: 'GitLab',
		authDomain: 'gitlab.com',
		color: '#FC6D26',
		tools: [read('List projects'), read('Read a merge request'), read('Read pipeline status'), write('Leave a review comment')],
	}),
	app({
		id: 'bitbucket',
		name: 'Bitbucket',
		description: 'Repositories and pull requests',
		categoryId: 'code-ci',
		vendor: 'Atlassian',
		authDomain: 'bitbucket.org',
		color: '#2684FF',
		tools: [read('List repositories'), read('Read a pull request'), write('Leave a review comment')],
	}),
	app({
		id: 'circleci',
		name: 'CircleCI',
		description: 'Pipelines and job output',
		categoryId: 'code-ci',
		vendor: 'CircleCI',
		authDomain: 'app.circleci.com',
		tools: [read('List pipelines'), read('Read job output'), write('Rerun a workflow')],
	}),
	app({
		id: 'netlify',
		name: 'Netlify',
		description: 'Deploys and preview URLs',
		categoryId: 'code-ci',
		vendor: 'Netlify',
		authDomain: 'app.netlify.com',
		color: '#00AD9F',
		tools: [read('List deploys'), read('Read deploy output'), write('Start a deploy')],
	}),
	app({
		id: 'okta',
		name: 'Okta',
		description: 'Directory, groups and app assignments',
		categoryId: 'code-ci',
		vendor: 'Okta',
		authDomain: 'okta.com',
		color: '#007DC1',
		tools: [read('List users'), read('List groups'), write('Grant app access')],
	}),
	app({
		id: 'linear',
		name: 'Linear',
		description: 'Issues, projects and cycles',
		categoryId: 'issues',
		connected: true,
		vendor: 'Linear',
		authDomain: 'linear.app',
		color: '#5E6AD2',
		tools: [read('Search issues'), read('Read a cycle'), write('Create an issue'), write('Change issue state')],
	}),
	app({
		id: 'jira',
		name: 'Jira',
		description: 'Tickets, sprints and comments',
		categoryId: 'issues',
		vendor: 'Atlassian',
		authDomain: 'id.atlassian.com',
		color: '#0052CC',
		tools: [read('Search with JQL'), read('Read a ticket'), write('Transition a ticket'), write('Comment on a ticket')],
	}),
	app({
		id: 'asana',
		name: 'Asana',
		description: 'Tasks, projects and due dates',
		categoryId: 'issues',
		vendor: 'Asana',
		authDomain: 'app.asana.com',
		color: '#F06A6A',
		tools: [read('List tasks'), read('Read a project'), write('Add a task')],
	}),
	app({
		id: 'confluence',
		name: 'Confluence',
		description: 'Spaces and pages',
		categoryId: 'docs',
		vendor: 'Atlassian',
		authDomain: 'id.atlassian.com',
		color: '#1868DB',
		tools: [read('Search spaces'), read('Read a page'), write('Publish a page')],
	}),
	app({
		id: 'google-drive',
		name: 'Google Drive',
		description: 'Docs, sheets and folders',
		categoryId: 'docs',
		connected: true,
		vendor: 'Google',
		authDomain: 'accounts.google.com',
		color: '#1FA463',
		tools: [read('Search Drive'), read('Read a document'), read('Export a sheet')],
	}),
	app({
		id: 'coda',
		name: 'Coda',
		description: 'Docs and tables',
		categoryId: 'docs',
		vendor: 'Coda',
		authDomain: 'coda.io',
		color: '#F46A54',
		tools: [read('Read a doc'), read('Query a table'), write('Upsert table rows')],
	}),
	app({
		id: 'intercom',
		name: 'Intercom',
		description: 'Customer conversations and contacts',
		categoryId: 'customer-voice',
		vendor: 'Intercom',
		authDomain: 'app.intercom.com',
		color: '#286EFA',
		tools: [read('Search conversations'), read('Read a contact'), write('Reply to a conversation'), write('Tag a conversation')],
	}),
	app({
		id: 'zendesk',
		name: 'Zendesk',
		description: 'Support tickets and requesters',
		categoryId: 'customer-voice',
		connected: true,
		vendor: 'Zendesk',
		authDomain: 'zendesk.com',
		color: '#17494D',
		tools: [read('Search tickets'), read('Read a requester'), write('Change ticket status')],
	}),
	app({
		id: 'typeform',
		name: 'Typeform',
		description: 'Survey responses',
		categoryId: 'customer-voice',
		vendor: 'Typeform',
		authDomain: 'admin.typeform.com',
		tools: [read('List forms'), read('Read responses')],
	}),
	app({
		id: 'amplitude',
		name: 'Amplitude',
		description: 'Product events, funnels and cohorts',
		categoryId: 'analytics',
		connected: true,
		vendor: 'Amplitude',
		authDomain: 'analytics.amplitude.com',
		color: '#1E61F0',
		tools: [read('Query events'), read('Read funnels'), read('Read cohorts')],
	}),
	app({
		id: 'mixpanel',
		name: 'Mixpanel',
		description: 'Product reports and cohorts',
		categoryId: 'analytics',
		vendor: 'Mixpanel',
		authDomain: 'mixpanel.com',
		color: '#7856FF',
		tools: [read('Run a report'), read('Read cohorts')],
	}),
	app({
		id: 'google-analytics',
		name: 'Google Analytics',
		description: 'Traffic, acquisition and conversions',
		categoryId: 'analytics',
		vendor: 'Google',
		authDomain: 'accounts.google.com',
		color: '#E37400',
		tools: [read('Run a report'), read('Read realtime users'), read('Read conversions')],
	}),
	app({
		id: 'posthog',
		name: 'PostHog',
		description: 'Events, feature flags and session replays',
		categoryId: 'analytics',
		vendor: 'PostHog',
		authDomain: 'app.posthog.com',
		color: '#F54E00',
		tools: [read('Query events'), read('Read session replays'), read('Read feature flags'), write('Change a feature flag')],
	}),
	app({
		id: 'metabase',
		name: 'Metabase',
		description: 'Saved questions and dashboards',
		categoryId: 'analytics',
		connected: true,
		vendor: 'Metabase',
		authDomain: 'metabase.com',
		color: '#509EE3',
		tools: [read('Run a saved question'), read('Read a dashboard'), read('List collections')],
	}),
	app({
		id: 'sentry',
		name: 'Sentry',
		description: 'Errors and releases',
		categoryId: 'monitoring',
		vendor: 'Sentry',
		authDomain: 'sentry.io',
		color: '#6C5FC7',
		tools: [read('Search issues'), read('Read an event'), write('Assign an issue'), write('Resolve an issue')],
	}),
	app({
		id: 'datadog',
		name: 'Datadog',
		description: 'Metrics, monitors and logs',
		categoryId: 'monitoring',
		vendor: 'Datadog',
		authDomain: 'app.datadoghq.com',
		color: '#632CA6',
		tools: [read('Query metrics'), read('List monitors'), write('Mute a monitor')],
	}),
	app({
		id: 'pagerduty',
		name: 'PagerDuty',
		description: 'Incidents and on-call',
		categoryId: 'monitoring',
		vendor: 'PagerDuty',
		authDomain: 'pagerduty.com',
		color: '#06AC38',
		tools: [read('List incidents'), read('Read the on-call rota'), write('Acknowledge an incident'), write('Open an incident')],
	}),
	app({
		id: 'grafana',
		name: 'Grafana',
		description: 'Dashboards and alerting',
		categoryId: 'monitoring',
		vendor: 'Grafana',
		authDomain: 'grafana.com',
		color: '#F46800',
		tools: [read('Read a dashboard'), read('List alert rules'), read('Query a data source')],
	}),
	app({
		id: 'gmail',
		name: 'Gmail',
		description: 'Email threads and drafts',
		categoryId: 'communication',
		connected: true,
		vendor: 'Google',
		authDomain: 'accounts.google.com',
		color: '#EA4335',
		tools: [read('Search mail'), read('Read a thread'), write('Write a draft'), write('Send an email')],
	}),
	app({
		id: 'google-calendar',
		name: 'Google Calendar',
		description: 'Events and availability',
		categoryId: 'communication',
		connected: true,
		vendor: 'Google',
		authDomain: 'accounts.google.com',
		color: '#4285F4',
		tools: [read('List events'), read('Find availability'), write('Book an event')],
	}),
	app({
		id: 'teams',
		name: 'Microsoft Teams',
		description: 'Channels, chats and meetings',
		categoryId: 'communication',
		vendor: 'Microsoft',
		authDomain: 'login.microsoftonline.com',
		color: '#5059C9',
		tools: [read('Read channel messages'), read('Read meeting notes'), write('Post a message')],
	}),
	app({
		id: 'discord',
		name: 'Discord',
		description: 'Server channels',
		categoryId: 'communication',
		vendor: 'Discord',
		authDomain: 'discord.com',
		color: '#5865F2',
		tools: [read('Read channel messages'), write('Post a message')],
	}),
	app({
		id: 'zoom',
		name: 'Zoom',
		description: 'Meetings and recordings',
		categoryId: 'communication',
		vendor: 'Zoom',
		authDomain: 'zoom.us',
		color: '#0B5CFF',
		tools: [read('List meetings'), read('Read a recording'), write('Schedule a meeting')],
	}),
];
